### ISSUE TITLE
Change to getch causes examples to break

### ISSUE THREAD

**Issue by Blotz** [shade40/Slate#1]
The mouse playground example was broken in [this commit](https://github.com/shade40/Slate/commit/fc9d7a12431468b785e9a33a8acb981a9be34913) where changes were made to the getch function which caused the return type to change.
This causes it to crash when calling `startswith`.

**Comment by bczsalba** [comment]
Hey, sorry for the delay! I got caught up in having to finish university.

Fixed this now, the behaviour (obviously) was intentional but the example was outdated.

Thanks for trying the library!
